apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-message-broker-master
  labels:
    app: redis-message-broker-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-message-broker-master
  template:
    metadata:
      labels:
        app: redis-message-broker-master
    spec:
      containers:
      - name: main
        image: redis
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: 1Gi
            cpu: 1
        ports:
        - containerPort: 6379

---

kind: Service
apiVersion: v1
metadata:
  name: redis-message-broker-master
  labels:
    app: redis-message-broker-master
spec:
  type: ClusterIP
  selector:
    app: redis-message-broker-master
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
