forwarder:
  sync:
    user_port: 5005
    user_hostname: "localhost"
    use_grpc: false
    predict_route: "/predict"
    healthcheck_route: "/readyz"
    batch_route: null
    model_engine_unwrap: false
    serialize_results_as_string: false
    wrap_response: false
    forward_http_status: true
  async:
    user_port: 5005
    user_hostname: "localhost"
    use_grpc: false
    predict_route: "/predict"
    healthcheck_route: "/readyz"
    batch_route: null
    model_engine_unwrap: false
    serialize_results_as_string: false
    wrap_response: false
