repos:
  - repo: https://github.com/psf/black
    # Make sure to update requirements-dev-extra.txt to match versions!
    rev: 22.12.0
    hooks:
      - id: black
        name: "python:black"
        entry: black --config .black.toml
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.278
    hooks:
      - id: ruff
        name: "python:ruff"
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: "python:isort"
  - repo: https://github.com/jazzband/pip-tools
    rev: 6.6.2
    hooks:
      - id: pip-compile
        files: server/requirements\.(in|txt)
        args:
          [
            server/requirements.in,
            --allow-unsafe,
            --no-emit-index-url,
            --no-emit-trusted-host,
            --index-url=https://pypi.org/simple,
          ]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0  # https://github.com/pre-commit/pre-commit-hooks/releases
    hooks:
      - id: check-added-large-files
        args:
          - '--maxkb=1024' # no more than 1 MB, which is already quite generous!
      - id: check-ast
        language: python
      - id: check-case-conflict
        language: python
      - id: check-json
        language: python
      - id: check-merge-conflict
        language: python
      - id: check-shebang-scripts-are-executable
        language: python
      - id: check-symlinks
        language: python
      - id: check-toml
        language: python
