site_name: LLM Engine
site_description: The open source engine for fine-tuning large language models.

theme:
  name: material
  palette:
    - scheme: default
      primary: white
      accent: deep purple

    # - scheme: slate
    #   primary: blue grey
    #   accent: indigo
    #   toggle:
    #     icon: material/lightbulb-outline
    #     name: Switch to light mode
  font:
    text: Inter
    code: IBM Plex Mono
  features:
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotate
    - navigation.expand
    - content.code.copy
  icon:
    repo: fontawesome/brands/github
  logo: https://raw.githubusercontent.com/scaleapi/llm-engine/main/docs/_static/favicon-32x32.png
  favicon: https://raw.githubusercontent.com/scaleapi/llm-engine/main/docs/_static/favicon-32x32.png
  language: en

repo_name: llm-engine
repo_url: https://github.com/scaleapi/llm-engine
edit_uri: ""
nav:
  - Introduction: index.md
  - "Getting Started": getting_started.md
  - "Model Zoo": model_zoo.md
  - "Guides":
      - "Completions": guides/completions.md
      - "Fine-tuning": guides/fine_tuning.md
      - "Rate limits": guides/rate_limits.md
      - "Self Hosting": guides/self_hosting.md
  - "API":
      - "API Reference": api/python_client.md
      - "Data Type Reference": api/data_types.md
      - "Error handling": api/error_handling.md
  - "Integrations": integrations.md
  - "Pricing": pricing.md
  - "Contributing": contributing.md
#  - "FAQ": faq.md

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
      noclasses: true
      pygments_style: "default"
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - mdx_include
  - def_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.striphtml:
      strip_comments: true
      strip_js_on_attributes: false
  - neoteroi.cards
  - footnotes

plugins:
  - search
  - mkdocstrings:
      watch:
        - clients/python/llmengine
      handlers:
        python:
          options:
            separate_signature: true
            line_length: 60
          rendering:
            show_root_heading: true
            show_root_full_path: false
            show_source: false
            heading_level: 2
            merge_init_into_class: true
            show_signature_annotations: true
            separate_signature: true
#  - mkdocs-simple-hooks:
#      hooks:
#        on_pre_build: "docs.plugins:on_pre_build"
#        on_files: "docs.plugins:on_files"
#        on_page_markdown: "docs.plugins:on_page_markdown"

extra_css:
  - stylesheets/index.css
  - assets/css/extra.css
  - assets/css/neoteroi.css

extra:
  analytics:
    provider: google
    property: G-N54ZLW5PGC
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.
