{{- if .Values.aws  }}
{{- if eq .Values.aws.configMap.create true }}
{{- $name := .Values.aws.configMap.name }}
{{- $profileName := .Values.aws.profileName }}
{{- $annotations := .Values.serviceAccount.annotations }}
{{- $labels := include "modelEngine.labels" . }}
{{- range $namespace := .Values.aws.configMap.namespaces }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $name }}
  namespace: {{- printf " %s" $namespace }}
  labels:
    {{- $labels | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-2"
data:
  config: |-
    [profile {{ $profileName }}]
    role_arn = {{ index $annotations "eks.amazonaws.com/role-arn" }}
    web_identity_token_file = /var/run/secrets/eks.amazonaws.com/serviceaccount/token
---
{{- end }}
{{- end }}
{{- end }}
