{{- if not .Values.serviceIdentifier }}
{{- range .Values.balloons }}
{{- if not (eq .acceleratorName "cpu") }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Chart.Name }}-balloon-{{ .acceleratorName }}
  labels:
    team: infra
    product: common-warm-nodes
spec:
  replicas: {{ .replicaCount }}
  selector:
    matchLabels:
      app: {{ $.Chart.Name }}-balloon-{{ .acceleratorName }}
      version: v1
  template:
    metadata:
      labels:
        app: {{ $.Chart.Name }}-balloon-{{ .acceleratorName }}
        product: common-warm-nodes
        team: infra
        env: {{ $.Values.context }}
        version: v1
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      nodeSelector:
        k8s.amazonaws.com/accelerator: {{ .acceleratorName }}
        {{- with $.Values.balloonNodeSelector }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      tolerations:
        - key: "nvidia.com/gpu"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - image: public.ecr.aws/ubuntu/ubuntu:latest
          imagePullPolicy: IfNotPresent
          name: main
          resources:
            limits:
              memory: 28Gi
              nvidia.com/gpu: 1
              cpu: 4
          command:
            - /bin/bash
            - -c
            - "while true; do sleep 30; done"
      terminationGracePeriodSeconds: 0
      priorityClassName: {{ $.Chart.Name }}-low-priority
---
{{- end }}
{{- end }}
{{- end }}