{{- $serviceAccountName := include "modelEngine.fullname" . }}
{{- $serviceAccountNamespaces := (include "modelEngine.serviceAccountNamespaces" . | fromYaml) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "modelEngine.fullname" . }}
  labels:
    {{- include "modelEngine.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  {{- range $namespace := (index $serviceAccountNamespaces "namespaces") }}
  - kind: ServiceAccount
    name: {{ $serviceAccountName }}
    namespace: {{ $namespace }}
  {{- end }}
