apiVersion: v1
kind: ConfigMap
metadata:
  name: model-engine-inference-framework-latest-config
  labels:
    product: common
    team: infra
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-2"
data:
  deepspeed: "latest"
  text_generation_inference: "latest"
  vllm: "latest"
  lightllm: "latest"
  tensorrt_llm: "latest"
