{{- if and (.Values.serviceTemplate) (.Values.serviceTemplate.createServiceAccount) (.Values.serviceTemplate.serviceAccountAnnotations) (.Values.serviceTemplate.serviceAccountName) (.Values.config.values.launch.endpoint_namespace)}}
{{- $annotations := .Values.serviceTemplate.serviceAccountAnnotations }}
{{- $inferenceServiceAccountName := .Values.serviceTemplate.serviceAccountName }}
{{- $inferenceServiceAccountNamespace := .Values.config.values.launch.endpoint_namespace }}
{{- $labels := include "modelEngine.labels" . }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{- printf " %s" $inferenceServiceAccountName }}
  namespace: {{- printf " %s" $inferenceServiceAccountNamespace }}
  labels:
    {{- $labels | nindent 4 }}
  {{- with $annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
{{- end }}