{{- if not .Values.serviceIdentifier }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-engine-balloon-t4
  labels:
    team: infra
    product: common-warm-nodes
spec:
  replicas: {{ .Values.replicaCount.balloonT4 }}
  selector:
    matchLabels:
      app: llm-engine-balloon-t4
      version: v1
  template:
    metadata:
      labels:
        app: llm-engine-balloon-t4
        product: common-warm-nodes
        team: infra
        env: {{ .Values.context }}
        version: v1
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      nodeSelector:
        k8s.amazonaws.com/accelerator: nvidia-tesla-t4
        node-lifecycle: normal
      tolerations:
        - key: "nvidia.com/gpu"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - image: public.ecr.aws/ubuntu/ubuntu:latest
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: main
          resources:
            limits:
              memory: 28Gi
              nvidia.com/gpu: 1
              cpu: 4
          command:
            - /bin/bash
            - -c
            - "while true; do sleep 30; done"
      terminationGracePeriodSeconds: 0
      priorityClassName: llm-engine-low-priority
{{- end }}
