{{- if .Values.autoscaling.vertical.enabled }}
apiVersion: "autoscaling.k8s.io/v1"
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "llmEngine.buildername" . }}
  labels:
    {{- include "llmEngine.labels" . | nindent 4 }}
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: {{ include "llmEngine.buildername" . }}
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
      - containerName: {{ include "llmEngine.buildername" . }}
        minAllowed:
          cpu: {{ .Values.autoscaling.vertical.minAllowed.cpu }}
          memory: {{ .Values.autoscaling.vertical.minAllowed.memory }}
        maxAllowed:
          cpu: {{ .Values.autoscaling.vertical.maxAllowed.cpu }}
          memory: {{ .Values.autoscaling.vertical.maxAllowed.memory }}
        controlledResources: ["cpu", "memory"]
{{- end }}
