{{- if .Values.config.values }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "llmEngine.fullname" . }}-service-config
  labels:
    {{- include "llmEngine.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-2"
data:
  llm_engine_service_config: |-
    {{- with .Values.config.values.llm_engine }}
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- end }}
  infra_service_config: |-
    env: {{ .Values.context | quote }}
    {{- with .Values.config.values.infra }}
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- end }}
{{- end }}
